# Generated by Django 5.0.4 on 2024-04-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dados_usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("email", models.TextField(max_length=255)),
                ("idade", models.IntegerField()),
            ],
        ),
    ]
